version: '3'
services:

  osrmcpy-jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    volumes:
      - ./:/usr/local/app
    ports:
      - '8889:8888'
    command: jupyter lab --NotebookApp.token= --ip=0.0.0.0 --no-browser --allow-root

  osrmcpy:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./config.env
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/local/app
    ports:
      - '5050:5000'
